version: '2'

services:
  src:
    build:
      context: .
      dockerfile: Dockerfile.development
    entrypoint: python3
    volumes:
      - .:/service
  tests:
    build:
      context: .
      dockerfile: Dockerfile.development
    entrypoint: python3 -m unittest discover tests/
    volumes:
      - .:/service
  lint:
    build:
      context: .
      dockerfile: Dockerfile.development
    entrypoint: flake8
    volumes:
      - .:/service